version: '3.8'

services:
  espresso-rabbitmq:
    # image: rabbitmq
    image: rabbitmq:3-management
    container_name: espresso-rabbitmq
    volumes:
      - espresso-rabbitmq-definitions:/etc/rabbitmq/definitions.json
      - espresso-rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - espresso-rabbitmq-logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - espresso

volumes:
  espresso-rabbitmq-definitions:
  espresso-rabbitmq-data:
  espresso-rabbitmq-logs:

networks:
  espresso:
