version: '3.8'
services:
  espresso-webapi:
    container_name: espresso-webapi
    image: espresso-webapi
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: source/server/WebApi/Espresso.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
    ports:
      - '8000:80'
    networks:
      - espresso

networks:
  espresso:
