
version: "3.8"
services:
    webapi:
        container_name: webapi
        build: 
            context: ../source
            dockerfile: Espresso.WebApi/Dockerfile
        ports:
            - "8000:80"
            - "8001:443"
        depends_on:
            - "database"
        restart: always
        environment:
            ASPNETCORE_ENVIRONMENT: ""
            APPCONFIGURATION__APIKEYS: ""
            CONNECTIONSTRINGS__DEFAULTCONNECTIONSTRING: ""
    parser:
        container_name: parser
        build: 
            context: ../source
            dockerfile: Espresso.ParserDeleter/Dockerfile
        depends_on:
            - "database"
            - "webapi"
        restart: always
        environment:
            DOTNET_ENVIRONMENT: ""
            CONNECTIONSTRINGS__DEFAULTCONNECTIONSTRING: "",
    database:
        container_name: database
        image: "microsoft/mssql-server-linux:2017-latest"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: ""
            ACCEPT_EULA: "Y"