name: espresso-workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  backend-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: Install dependencies
        run: dotnet restore source/Espresso.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore source/Espresso.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal source/Espresso.sln
  frontend-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm install
      - name: lint
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm run lint-frontend
      - name: test
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm run test-frontend:ci
  slack-notification:
    name: Workflow Failure Slack Notification
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Workflow Failure Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tech-bot
          SLACK_COLOR: '#EB0C13'
          SLACK_ICON: https://static.botsrv.com/website/img/quriobot_favicon.1727b193.png
          SLACK_MESSAGE: Test Fail
          SLACK_TITLE: ${{ github.workflow }} Workflow Failure
          SLACK_USERNAME: Backend CI/CD
        if: ${{ failure() }}
      - name: Workflow Success Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tech-bot
          SLACK_COLOR: '#0FEB0C'
          SLACK_ICON: https://mpng.subpng.com/20180410/xgw/kisspng-internet-bot-web-traffic-safe-5acd7c51dda2f4.1033986715234161459078.jpg
          # SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Success Test Success'
          SLACK_TITLE: ${{ github.workflow }} Workflow Success
          SLACK_USERNAME: Backend CI/CD
        if: ${{ success() }}
      - name: echo tests1
        run: echo env.WORKFLOW_CONCLUSION ${{ env.WORKFLOW_CONCLUSION }}
      - name: echo tests2
        run: echo github.workflow ${{ github.workflow }}
      - name: echo tests3
        run: echo github.action ${{ github.action }}
      - name: echo tests4
        run: echo job.status ${{ job.status }}
