name: espresso-workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  espresso-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: Install .NET Dependencies
        run: dotnet restore source/Espresso.sln
      - name: Build .NET
        run: dotnet build --configuration Release --no-restore source/Espresso.sln
      - name: Test .NET
        run: dotnet test --no-restore --verbosity normal source/Espresso.sln

      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install React Dependencies
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm install
      - name: Lint React
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm run lint-frontend
      - name: Test React
        working-directory: ./source/Espresso.WebApi/ClientApp
        run: npm run test-frontend:ci

      - uses: actions/checkout@v2
      - name: Failure Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tech-bot
          SLACK_COLOR: '#EB0C13'
          SLACK_ICON: https://mpng.subpng.com/20180410/xgw/kisspng-internet-bot-web-traffic-safe-5acd7c51dda2f4.1033986715234161459078.jpg
          SLACK_TITLE: Failure
          SLACK_MESSAGE: Workflow Failure
          SLACK_USERNAME: Backend CI/CD

        if: ${{ failure() }}
      - name: Success Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tech-bot
          SLACK_COLOR: '#0FEB0C'
          SLACK_ICON: https://static.botsrv.com/website/img/quriobot_favicon.1727b193.png
          SLACK_TITLE: Success
          SLACK_MESSAGE: Workflow Success
          SLACK_USERNAME: Backend CI/CD
        if: ${{ success() }}
